FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.16-openshift-4.9 AS builder
WORKDIR /go/src/github.com/openshift/local-storage-operator
COPY . .

FROM registry.ci.openshift.org/ocp/4.9:must-gather
COPY --from=builder /go/src/github.com/openshift/local-storage-operator/must-gather/* /usr/bin/
RUN chmod +x /usr/bin/gather

ENTRYPOINT /usr/bin/gather
