FROM registry.ci.openshift.org/ocp/4.8:must-gather AS builder

FROM registry.ci.openshift.org/ocp/4.8:cli

RUN microdnf -y install rsync

COPY --from=builder /usr/bin/oc /usr/bin/oc
COPY must-gather/* /usr/bin/

ENTRYPOINT /usr/bin/gather
