FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.18-openshift-4.11 AS builder
WORKDIR /go/src/github.com/openshift/local-storage-operator
COPY . .

FROM registry.ci.openshift.org/ocp/4.11:must-gather
COPY --from=builder /go/src/github.com/openshift/local-storage-operator/must-gather/* /usr/bin/
RUN chmod +x /usr/bin/gather

ENTRYPOINT /usr/bin/gather
