#!/bin/bash

subscriptionName="local-storage-operator"

lsoNamespace=$(/usr/bin/oc get subscription --all-namespaces | grep ${subscriptionName} | awk '{print $1}')
/usr/bin/oc adm inspect namespace/${lsoNamespace} --dest-dir=must-gather/

for I in $(/usr/bin/oc get crd | grep local.storage.openshift.io | awk '{print $1}'); do
    echo "Gathering data for CRD $I"
    /usr/bin/oc adm inspect $I --all-namespaces --dest-dir=must-gather/
done

# Nodes and PVs
/usr/bin/oc adm inspect nodes,persistentvolumes --dest-dir=must-gather/

exit 0
