apiVersion: v1
kind: Service
metadata:
  name: lso-metrics-exporter
  namespace: openshift-local-storage
  labels:
    app: lso-metrics-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: 8383
  selector:
    app: lso-metrics-exporter
