apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: local-operator-pv-binding
subjects:
  - kind: ServiceAccount
    name: local-storage-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: 'system:persistent-volume-provisioner'
  apiGroup: rbac.authorization.k8s.io
