kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-storage-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: local-storage-operator
subjects:
  - kind: ServiceAccount
    name: local-storage-operator
    namespace: default
