//go:build !ignore_autogenerated

/*
Copyright 2021 The Local Storage Operator Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1 "github.com/openshift/api/operator/v1"
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInclusionSpec) DeepCopyInto(out *DeviceInclusionSpec) {
	*out = *in
	if in.DeviceTypes != nil {
		in, out := &in.DeviceTypes, &out.DeviceTypes
		*out = make([]DeviceType, len(*in))
		copy(*out, *in)
	}
	if in.DeviceMechanicalProperties != nil {
		in, out := &in.DeviceMechanicalProperties, &out.DeviceMechanicalProperties
		*out = make([]DeviceMechanicalProperty, len(*in))
		copy(*out, *in)
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vendors != nil {
		in, out := &in.Vendors, &out.Vendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInclusionSpec.
func (in *DeviceInclusionSpec) DeepCopy() *DeviceInclusionSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceInclusionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveredDevice) DeepCopyInto(out *DiscoveredDevice) {
	*out = *in
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveredDevice.
func (in *DiscoveredDevice) DeepCopy() *DiscoveredDevice {
	if in == nil {
		return nil
	}
	out := new(DiscoveredDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscovery) DeepCopyInto(out *LocalVolumeDiscovery) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscovery.
func (in *LocalVolumeDiscovery) DeepCopy() *LocalVolumeDiscovery {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeDiscovery) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoveryList) DeepCopyInto(out *LocalVolumeDiscoveryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LocalVolumeDiscovery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoveryList.
func (in *LocalVolumeDiscoveryList) DeepCopy() *LocalVolumeDiscoveryList {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoveryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeDiscoveryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoveryResult) DeepCopyInto(out *LocalVolumeDiscoveryResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoveryResult.
func (in *LocalVolumeDiscoveryResult) DeepCopy() *LocalVolumeDiscoveryResult {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoveryResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeDiscoveryResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoveryResultList) DeepCopyInto(out *LocalVolumeDiscoveryResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LocalVolumeDiscoveryResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoveryResultList.
func (in *LocalVolumeDiscoveryResultList) DeepCopy() *LocalVolumeDiscoveryResultList {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoveryResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeDiscoveryResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoveryResultSpec) DeepCopyInto(out *LocalVolumeDiscoveryResultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoveryResultSpec.
func (in *LocalVolumeDiscoveryResultSpec) DeepCopy() *LocalVolumeDiscoveryResultSpec {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoveryResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoveryResultStatus) DeepCopyInto(out *LocalVolumeDiscoveryResultStatus) {
	*out = *in
	if in.DiscoveredDevices != nil {
		in, out := &in.DiscoveredDevices, &out.DiscoveredDevices
		*out = make([]DiscoveredDevice, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoveryResultStatus.
func (in *LocalVolumeDiscoveryResultStatus) DeepCopy() *LocalVolumeDiscoveryResultStatus {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoveryResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoverySpec) DeepCopyInto(out *LocalVolumeDiscoverySpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoverySpec.
func (in *LocalVolumeDiscoverySpec) DeepCopy() *LocalVolumeDiscoverySpec {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeDiscoveryStatus) DeepCopyInto(out *LocalVolumeDiscoveryStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]operatorv1.OperatorCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeDiscoveryStatus.
func (in *LocalVolumeDiscoveryStatus) DeepCopy() *LocalVolumeDiscoveryStatus {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeDiscoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSet) DeepCopyInto(out *LocalVolumeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSet.
func (in *LocalVolumeSet) DeepCopy() *LocalVolumeSet {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSetList) DeepCopyInto(out *LocalVolumeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LocalVolumeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSetList.
func (in *LocalVolumeSetList) DeepCopy() *LocalVolumeSetList {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSetSpec) DeepCopyInto(out *LocalVolumeSetSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxDeviceCount != nil {
		in, out := &in.MaxDeviceCount, &out.MaxDeviceCount
		*out = new(int32)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeviceInclusionSpec != nil {
		in, out := &in.DeviceInclusionSpec, &out.DeviceInclusionSpec
		*out = new(DeviceInclusionSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSetSpec.
func (in *LocalVolumeSetSpec) DeepCopy() *LocalVolumeSetSpec {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSetStatus) DeepCopyInto(out *LocalVolumeSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]operatorv1.OperatorCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TotalProvisionedDeviceCount != nil {
		in, out := &in.TotalProvisionedDeviceCount, &out.TotalProvisionedDeviceCount
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSetStatus.
func (in *LocalVolumeSetStatus) DeepCopy() *LocalVolumeSetStatus {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSetStatus)
	in.DeepCopyInto(out)
	return out
}
