// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	operatorv1 "github.com/openshift/api/operator/v1"
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInclusionSpec) DeepCopyInto(out *DeviceInclusionSpec) {
	*out = *in
	if in.DeviceTypes != nil {
		in, out := &in.DeviceTypes, &out.DeviceTypes
		*out = make([]DeviceType, len(*in))
		copy(*out, *in)
	}
	if in.DeviceMechanicalProperties != nil {
		in, out := &in.DeviceMechanicalProperties, &out.DeviceMechanicalProperties
		*out = make([]DeviceMechanicalProperty, len(*in))
		copy(*out, *in)
	}
	if in.MinSize != nil {
		in, out := &in.MinSize, &out.MinSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxSize != nil {
		in, out := &in.MaxSize, &out.MaxSize
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Models != nil {
		in, out := &in.Models, &out.Models
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vendors != nil {
		in, out := &in.Vendors, &out.Vendors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInclusionSpec.
func (in *DeviceInclusionSpec) DeepCopy() *DeviceInclusionSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceInclusionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSet) DeepCopyInto(out *LocalVolumeSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSet.
func (in *LocalVolumeSet) DeepCopy() *LocalVolumeSet {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSetList) DeepCopyInto(out *LocalVolumeSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LocalVolumeSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSetList.
func (in *LocalVolumeSetList) DeepCopy() *LocalVolumeSetList {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LocalVolumeSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSetSpec) DeepCopyInto(out *LocalVolumeSetSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.NodeSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.MaxDeviceCount != nil {
		in, out := &in.MaxDeviceCount, &out.MaxDeviceCount
		*out = new(int32)
		**out = **in
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeviceInclusionSpec != nil {
		in, out := &in.DeviceInclusionSpec, &out.DeviceInclusionSpec
		*out = new(DeviceInclusionSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSetSpec.
func (in *LocalVolumeSetSpec) DeepCopy() *LocalVolumeSetSpec {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSetSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalVolumeSetStatus) DeepCopyInto(out *LocalVolumeSetStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]operatorv1.OperatorCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TotalProvisionedDeviceCount != nil {
		in, out := &in.TotalProvisionedDeviceCount, &out.TotalProvisionedDeviceCount
		*out = new(int32)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalVolumeSetStatus.
func (in *LocalVolumeSetStatus) DeepCopy() *LocalVolumeSetStatus {
	if in == nil {
		return nil
	}
	out := new(LocalVolumeSetStatus)
	in.DeepCopyInto(out)
	return out
}
